import type { INodeProperties } from 'n8n-workflow';

export const nfeOperations: INodeProperties[] = [
	{
		displayName: 'Operacao',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['nfe'],
			},
		},
		options: [
			{
				name: 'Criar',
				value: 'create',
				description: 'Cria uma nova NFe',
				action: 'Criar uma NFe',
			},
			{
				name: 'Deletar',
				value: 'delete',
				description: 'Deleta uma NFe',
				action: 'Deletar uma NFe',
			},
			{
				name: 'Enviar',
				value: 'send',
				description: 'Envia uma NFe para a SEFAZ',
				action: 'Enviar uma NFe',
			},
			{
				name: 'Estornar Contas',
				value: 'reverseAccounts',
				description: 'Estorna as contas de uma NFe',
				action: 'Estornar contas de uma NFe',
			},
			{
				name: 'Estornar Estoque',
				value: 'reverseStock',
				description: 'Estorna o estoque de uma NFe',
				action: 'Estornar estoque de uma NFe',
			},
			{
				name: 'Lancar Contas',
				value: 'postAccounts',
				description: 'Lanca as contas de uma NFe',
				action: 'Lancar contas de uma NFe',
			},
			{
				name: 'Lancar Estoque',
				value: 'postStock',
				description: 'Lanca o estoque de uma NFe',
				action: 'Lancar estoque de uma NFe',
			},
			{
				name: 'Obter',
				value: 'get',
				description: 'Obtem uma NFe pelo ID',
				action: 'Obter uma NFe',
			},
			{
				name: 'Obter Todos',
				value: 'getAll',
				description: 'Obtem todas as NFes',
				action: 'Obter todas as NFes',
			},
			{
				name: 'Atualizar',
				value: 'update',
				description: 'Atualiza uma NFe',
				action: 'Atualizar uma NFe',
			},
		],
		default: 'getAll',
	},
];

export const nfeFields: INodeProperties[] = [
	// ----------------------------------
	//         nfe: nfeId
	// ----------------------------------
	{
		displayName: 'ID da NFe',
		name: 'nfeId',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['nfe'],
				operation: [
					'get',
					'update',
					'delete',
					'send',
					'postAccounts',
					'reverseAccounts',
					'postStock',
					'reverseStock',
				],
			},
		},
		description: 'ID da NFe',
	},

	// ----------------------------------
	//         nfe: create - nfeData
	// ----------------------------------
	{
		displayName: 'Dados da NFe',
		name: 'nfeData',
		type: 'collection',
		placeholder: 'Adicionar Campo',
		default: {},
		displayOptions: {
			show: {
				resource: ['nfe'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Tipo',
				name: 'tipo',
				type: 'options',
				options: [
					{ name: 'Entrada', value: 0 },
					{ name: 'Saida', value: 1 },
				],
				default: 1,
				description: 'Tipo da NFe (entrada ou saida)',
			},
			{
				displayName: 'ID Natureza da Operacao',
				name: 'naturezaOperacao',
				type: 'number',
				default: 0,
				description: 'ID da natureza da operacao',
			},
			{
				displayName: 'Finalidade',
				name: 'finalidade',
				type: 'options',
				options: [
					{ name: 'Normal', value: 1 },
					{ name: 'Complementar', value: 2 },
					{ name: 'Ajuste', value: 3 },
					{ name: 'Devolucao', value: 4 },
				],
				default: 1,
				description: 'Finalidade da NFe',
			},
			{
				displayName: 'Data',
				name: 'data',
				type: 'string',
				default: '',
				description: 'Data de emissao da NFe (AAAA-MM-DD)',
			},
			{
				displayName: 'Contato',
				name: 'contato',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Adicionar Contato',
				options: [
					{
						displayName: 'Dados do Contato',
						name: 'contatoData',
						values: [
							{
								displayName: 'ID do Contato',
								name: 'id',
								type: 'number',
								default: 0,
								description: 'ID do contato vinculado a NFe',
							},
							{
								displayName: 'Nome',
								name: 'nome',
								type: 'string',
								default: '',
								description: 'Nome do contato',
							},
							{
								displayName: 'Tipo Pessoa',
								name: 'tipoPessoa',
								type: 'options',
								options: [
									{ name: 'Juridica', value: 'J' },
									{ name: 'Fisica', value: 'F' },
									{ name: 'Estrangeiro', value: 'E' },
								],
								default: 'F',
								description: 'Tipo de pessoa do contato',
							},
							{
								displayName: 'Numero Documento',
								name: 'numeroDocumento',
								type: 'string',
								default: '',
								description: 'CPF ou CNPJ do contato',
							},
							{
								displayName: 'Contribuinte',
								name: 'contribuinte',
								type: 'options',
								options: [
									{ name: 'Contribuinte ICMS', value: 1 },
									{ name: 'Contribuinte isento', value: 2 },
									{ name: 'Nao contribuinte', value: 9 },
								],
								default: 9,
								description: 'Indicador de contribuinte',
							},
							{
								displayName: 'IE',
								name: 'ie',
								type: 'string',
								default: '',
								description: 'Inscricao estadual',
							},
						],
					},
				],
				description: 'Dados do contato vinculado a NFe',
			},
			{
				displayName: 'Itens',
				name: 'itens',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				default: {},
				placeholder: 'Adicionar Item',
				options: [
					{
						displayName: 'Item',
						name: 'itemData',
						values: [
							{
								displayName: 'ID do Produto',
								name: 'produto',
								type: 'number',
								default: 0,
								description: 'ID do produto',
							},
							{
								displayName: 'Descricao',
								name: 'descricao',
								type: 'string',
								default: '',
								description: 'Descricao do item',
							},
							{
								displayName: 'Codigo',
								name: 'codigo',
								type: 'string',
								default: '',
								description: 'Codigo do produto/item',
							},
							{
								displayName: 'Quantidade',
								name: 'quantidade',
								type: 'number',
								typeOptions: { numberPrecision: 4 },
								default: 1,
								description: 'Quantidade do item',
							},
							{
								displayName: 'Valor Unitario',
								name: 'valor',
								type: 'number',
								typeOptions: { numberPrecision: 10 },
								default: 0,
								description: 'Valor unitario do item',
							},
							{
								displayName: 'Unidade',
								name: 'unidade',
								type: 'string',
								default: 'UN',
								description: 'Unidade de medida do item',
							},
							{
								displayName: 'Desconto',
								name: 'desconto',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
								description: 'Desconto no item',
							},
							{
								displayName: 'NCM',
								name: 'ncm',
								type: 'string',
								default: '',
								description: 'Codigo NCM do item',
							},
							{
								displayName: 'CFOP',
								name: 'cfop',
								type: 'string',
								default: '',
								description: 'Codigo CFOP do item',
							},
							{
								displayName: 'Origem',
								name: 'origem',
								type: 'options',
								options: [
									{ name: '0 - Nacional', value: 0 },
									{ name: '1 - Estrangeira (importacao direta)', value: 1 },
									{ name: '2 - Estrangeira (adquirida no mercado interno)', value: 2 },
								],
								default: 0,
								description: 'Origem da mercadoria',
							},
							{
								displayName: 'Tipo Tributacao',
								name: 'tipo',
								type: 'string',
								default: '',
								description: 'Tipo de tributacao (CST ou CSOSN)',
							},
						],
					},
				],
				description: 'Itens da NFe',
			},
			{
				displayName: 'Parcelas',
				name: 'parcelas',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				default: {},
				placeholder: 'Adicionar Parcela',
				options: [
					{
						displayName: 'Parcela',
						name: 'parcelaData',
						values: [
							{
								displayName: 'Data de Vencimento',
								name: 'dataVencimento',
								type: 'string',
								default: '',
								description: 'Data de vencimento da parcela (AAAA-MM-DD)',
							},
							{
								displayName: 'Valor',
								name: 'valor',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
								description: 'Valor da parcela',
							},
							{
								displayName: 'Observacoes',
								name: 'observacoes',
								type: 'string',
								default: '',
								description: 'Observacoes da parcela',
							},
							{
								displayName: 'ID Forma de Pagamento',
								name: 'formaPagamento',
								type: 'number',
								default: 0,
								description: 'ID da forma de pagamento',
							},
						],
					},
				],
				description: 'Parcelas da NFe',
			},
			{
				displayName: 'Transporte',
				name: 'transporte',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Adicionar Transporte',
				options: [
					{
						displayName: 'Dados do Transporte',
						name: 'transporteData',
						values: [
							{
								displayName: 'Frete por Conta',
								name: 'fretePorConta',
								type: 'options',
								options: [
									{ name: 'Remetente (CIF)', value: 0 },
									{ name: 'Destinatario (FOB)', value: 1 },
									{ name: 'Terceiros', value: 2 },
									{ name: 'Proprio Remetente', value: 3 },
									{ name: 'Proprio Destinatario', value: 4 },
									{ name: 'Sem transporte', value: 9 },
								],
								default: 9,
								description: 'Modalidade de frete',
							},
							{
								displayName: 'Frete',
								name: 'frete',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
								description: 'Valor do frete',
							},
							{
								displayName: 'ID Contato Transportadora',
								name: 'transportadora',
								type: 'number',
								default: 0,
								description: 'ID do contato da transportadora',
							},
							{
								displayName: 'Quantidade de Volumes',
								name: 'quantidadeVolumes',
								type: 'number',
								default: 0,
								description: 'Quantidade de volumes',
							},
							{
								displayName: 'Peso Bruto',
								name: 'pesoBruto',
								type: 'number',
								typeOptions: { numberPrecision: 3 },
								default: 0,
								description: 'Peso bruto total',
							},
							{
								displayName: 'Peso Liquido',
								name: 'pesoLiquido',
								type: 'number',
								typeOptions: { numberPrecision: 3 },
								default: 0,
								description: 'Peso liquido total',
							},
							{
								displayName: 'Especie dos Volumes',
								name: 'especie',
								type: 'string',
								default: '',
								description: 'Especie dos volumes (ex: caixa, pacote)',
							},
							{
								displayName: 'Marca dos Volumes',
								name: 'marca',
								type: 'string',
								default: '',
								description: 'Marca dos volumes',
							},
							{
								displayName: 'Numeracao dos Volumes',
								name: 'numeracao',
								type: 'string',
								default: '',
								description: 'Numeracao dos volumes',
							},
						],
					},
				],
				description: 'Dados de transporte da NFe',
			},
			{
				displayName: 'Observacoes',
				name: 'observacoes',
				type: 'string',
				default: '',
				description: 'Observacoes da NFe',
			},
			{
				displayName: 'Desconto',
				name: 'desconto',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor do desconto',
			},
			{
				displayName: 'Outras Despesas',
				name: 'outrasDespesas',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor de outras despesas',
			},
			{
				displayName: 'ID Loja',
				name: 'loja',
				type: 'number',
				default: 0,
				description: 'ID da loja',
			},
		],
	},

	// ----------------------------------
	//         nfe: update - updateFields
	// ----------------------------------
	{
		displayName: 'Campos para Atualizar',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Adicionar Campo',
		default: {},
		displayOptions: {
			show: {
				resource: ['nfe'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Tipo',
				name: 'tipo',
				type: 'options',
				options: [
					{ name: 'Entrada', value: 0 },
					{ name: 'Saida', value: 1 },
				],
				default: 1,
				description: 'Tipo da NFe',
			},
			{
				displayName: 'ID Natureza da Operacao',
				name: 'naturezaOperacao',
				type: 'number',
				default: 0,
				description: 'ID da natureza da operacao',
			},
			{
				displayName: 'Finalidade',
				name: 'finalidade',
				type: 'options',
				options: [
					{ name: 'Normal', value: 1 },
					{ name: 'Complementar', value: 2 },
					{ name: 'Ajuste', value: 3 },
					{ name: 'Devolucao', value: 4 },
				],
				default: 1,
				description: 'Finalidade da NFe',
			},
			{
				displayName: 'Data',
				name: 'data',
				type: 'string',
				default: '',
				description: 'Data de emissao da NFe (AAAA-MM-DD)',
			},
			{
				displayName: 'Contato',
				name: 'contato',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Adicionar Contato',
				options: [
					{
						displayName: 'Dados do Contato',
						name: 'contatoData',
						values: [
							{
								displayName: 'ID do Contato',
								name: 'id',
								type: 'number',
								default: 0,
							},
							{
								displayName: 'Nome',
								name: 'nome',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Tipo Pessoa',
								name: 'tipoPessoa',
								type: 'options',
								options: [
									{ name: 'Juridica', value: 'J' },
									{ name: 'Fisica', value: 'F' },
									{ name: 'Estrangeiro', value: 'E' },
								],
								default: 'F',
							},
							{
								displayName: 'Numero Documento',
								name: 'numeroDocumento',
								type: 'string',
								default: '',
							},
						],
					},
				],
			},
			{
				displayName: 'Itens',
				name: 'itens',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				default: {},
				placeholder: 'Adicionar Item',
				options: [
					{
						displayName: 'Item',
						name: 'itemData',
						values: [
							{
								displayName: 'Indice do Item',
								name: 'indice',
								type: 'number',
								default: 0,
								description: 'Indice (posicao) do item a ser atualizado (comeca em 0)',
							},
							{
								displayName: 'ID do Produto',
								name: 'produto',
								type: 'number',
								default: 0,
							},
							{
								displayName: 'Descricao',
								name: 'descricao',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Codigo',
								name: 'codigo',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Quantidade',
								name: 'quantidade',
								type: 'number',
								typeOptions: { numberPrecision: 4 },
								default: 1,
							},
							{
								displayName: 'Valor Unitario',
								name: 'valor',
								type: 'number',
								typeOptions: { numberPrecision: 10 },
								default: 0,
							},
							{
								displayName: 'Unidade',
								name: 'unidade',
								type: 'string',
								default: 'UN',
							},
							{
								displayName: 'NCM',
								name: 'ncm',
								type: 'string',
								default: '',
							},
							{
								displayName: 'CFOP',
								name: 'cfop',
								type: 'string',
								default: '',
							},
						],
					},
				],
			},
			{
				displayName: 'Parcelas',
				name: 'parcelas',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				default: {},
				placeholder: 'Adicionar Parcela',
				options: [
					{
						displayName: 'Parcela',
						name: 'parcelaData',
						values: [
							{
								displayName: 'Indice da Parcela',
								name: 'indice',
								type: 'number',
								default: 0,
								description: 'Indice (posicao) da parcela a ser atualizada (comeca em 0)',
							},
							{
								displayName: 'Data de Vencimento',
								name: 'dataVencimento',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Valor',
								name: 'valor',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
							},
							{
								displayName: 'Observacoes',
								name: 'observacoes',
								type: 'string',
								default: '',
							},
							{
								displayName: 'ID Forma de Pagamento',
								name: 'formaPagamento',
								type: 'number',
								default: 0,
							},
						],
					},
				],
			},
			{
				displayName: 'Transporte',
				name: 'transporte',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Adicionar Transporte',
				options: [
					{
						displayName: 'Dados do Transporte',
						name: 'transporteData',
						values: [
							{
								displayName: 'Frete por Conta',
								name: 'fretePorConta',
								type: 'options',
								options: [
									{ name: 'Remetente (CIF)', value: 0 },
									{ name: 'Destinatario (FOB)', value: 1 },
									{ name: 'Terceiros', value: 2 },
									{ name: 'Proprio Remetente', value: 3 },
									{ name: 'Proprio Destinatario', value: 4 },
									{ name: 'Sem transporte', value: 9 },
								],
								default: 9,
							},
							{
								displayName: 'Frete',
								name: 'frete',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
							},
							{
								displayName: 'ID Contato Transportadora',
								name: 'transportadora',
								type: 'number',
								default: 0,
							},
							{
								displayName: 'Quantidade de Volumes',
								name: 'quantidadeVolumes',
								type: 'number',
								default: 0,
							},
							{
								displayName: 'Peso Bruto',
								name: 'pesoBruto',
								type: 'number',
								typeOptions: { numberPrecision: 3 },
								default: 0,
							},
							{
								displayName: 'Peso Liquido',
								name: 'pesoLiquido',
								type: 'number',
								typeOptions: { numberPrecision: 3 },
								default: 0,
							},
						],
					},
				],
			},
			{
				displayName: 'Observacoes',
				name: 'observacoes',
				type: 'string',
				default: '',
				description: 'Observacoes da NFe',
			},
			{
				displayName: 'Desconto',
				name: 'desconto',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor do desconto',
			},
			{
				displayName: 'Outras Despesas',
				name: 'outrasDespesas',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor de outras despesas',
			},
		],
	},

	// ----------------------------------
	//         nfe: getAll - returnAll
	// ----------------------------------
	{
		displayName: 'Retornar Todos',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['nfe'],
				operation: ['getAll'],
			},
		},
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limite',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: {
			minValue: 1,
			maxValue: 100,
		},
		displayOptions: {
			show: {
				resource: ['nfe'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		description: 'Max number of results to return',
	},

	// ----------------------------------
	//         nfe: getAll - filters
	// ----------------------------------
	{
		displayName: 'Filtros',
		name: 'filters',
		type: 'collection',
		placeholder: 'Adicionar Campo',
		default: {},
		displayOptions: {
			show: {
				resource: ['nfe'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Data Emissao Inicial',
				name: 'dataEmissaoInicial',
				type: 'string',
				default: '',
				description: 'Data de emissao inicial (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Emissao Final',
				name: 'dataEmissaoFinal',
				type: 'string',
				default: '',
				description: 'Data de emissao final (AAAA-MM-DD)',
			},
			{
				displayName: 'Situacao',
				name: 'situacao',
				type: 'options',
				options: [
					{ name: 'Pendente', value: 1 },
					{ name: 'Emitida', value: 2 },
					{ name: 'Cancelada', value: 3 },
					{ name: 'Denegada', value: 4 },
				],
				default: 1,
				description: 'Situacao da NFe',
			},
			{
				displayName: 'Tipo',
				name: 'tipo',
				type: 'options',
				options: [
					{ name: 'Entrada', value: 0 },
					{ name: 'Saida', value: 1 },
				],
				default: 1,
				description: 'Tipo da NFe',
			},
			{
				displayName: 'ID Contato',
				name: 'idContato',
				type: 'number',
				default: 0,
				description: 'ID do contato vinculado',
			},
			{
				displayName: 'ID Loja',
				name: 'idLoja',
				type: 'number',
				default: 0,
				description: 'ID da loja',
			},
			{
				displayName: 'Numero',
				name: 'numero',
				type: 'string',
				default: '',
				description: 'Numero da NFe',
			},
			{
				displayName: 'Serie',
				name: 'serie',
				type: 'string',
				default: '',
				description: 'Serie da NFe',
			},
			{
				displayName: 'Data Inclusao Inicial',
				name: 'dataInclusaoInicial',
				type: 'string',
				default: '',
				description: 'Data de inclusao inicial (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Inclusao Final',
				name: 'dataInclusaoFinal',
				type: 'string',
				default: '',
				description: 'Data de inclusao final (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Alteracao Inicial',
				name: 'dataAlteracaoInicial',
				type: 'string',
				default: '',
				description: 'Data de alteracao inicial (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Alteracao Final',
				name: 'dataAlteracaoFinal',
				type: 'string',
				default: '',
				description: 'Data de alteracao final (AAAA-MM-DD)',
			},
		],
	},
];
