import type { INodeProperties } from 'n8n-workflow';

export const pedidoVendaOperations: INodeProperties[] = [
	{
		displayName: 'Operacao',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['pedidoVenda'],
			},
		},
		options: [
			{
				name: 'Criar',
				value: 'create',
				description: 'Cria um novo pedido de venda',
				action: 'Criar um pedido de venda',
			},
			{
				name: 'Deletar',
				value: 'delete',
				description: 'Deleta um pedido de venda',
				action: 'Deletar um pedido de venda',
			},
			{
				name: 'Estornar Contas',
				value: 'reverseAccounts',
				description: 'Estorna as contas de um pedido de venda',
				action: 'Estornar contas de um pedido de venda',
			},
			{
				name: 'Estornar Estoque',
				value: 'reverseStock',
				description: 'Estorna o estoque de um pedido de venda',
				action: 'Estornar estoque de um pedido de venda',
			},
			{
				name: 'Gerar NFCe',
				value: 'generateNfce',
				description: 'Gera uma NFCe a partir do pedido de venda',
				action: 'Gerar NFCe de um pedido de venda',
			},
			{
				name: 'Gerar NFe',
				value: 'generateNfe',
				description: 'Gera uma NFe a partir do pedido de venda',
				action: 'Gerar NFe de um pedido de venda',
			},
			{
				name: 'Lancar Contas',
				value: 'postAccounts',
				description: 'Lanca as contas de um pedido de venda',
				action: 'Lancar contas de um pedido de venda',
			},
			{
				name: 'Lancar Estoque',
				value: 'postStock',
				description: 'Lanca o estoque de um pedido de venda',
				action: 'Lancar estoque de um pedido de venda',
			},
			{
				name: 'Obter',
				value: 'get',
				description: 'Obtem um pedido de venda pelo ID',
				action: 'Obter um pedido de venda',
			},
			{
				name: 'Obter Todos',
				value: 'getAll',
				description: 'Obtem todos os pedidos de venda',
				action: 'Obter todos os pedidos de venda',
			},
			{
				name: 'Atualizar',
				value: 'update',
				description: 'Atualiza um pedido de venda',
				action: 'Atualizar um pedido de venda',
			},
		],
		default: 'getAll',
	},
];

export const pedidoVendaFields: INodeProperties[] = [
	// ----------------------------------
	//         pedidoVenda: pedidoVendaId
	// ----------------------------------
	{
		displayName: 'ID do Pedido de Venda',
		name: 'pedidoVendaId',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['pedidoVenda'],
				operation: [
					'get',
					'update',
					'delete',
					'generateNfe',
					'generateNfce',
					'postAccounts',
					'reverseAccounts',
					'postStock',
					'reverseStock',
				],
			},
		},
		description: 'ID do pedido de venda',
	},

	// ----------------------------------
	//         pedidoVenda: create - orderData
	// ----------------------------------
	{
		displayName: 'Dados do Pedido',
		name: 'orderData',
		type: 'collection',
		placeholder: 'Adicionar Campo',
		default: {},
		displayOptions: {
			show: {
				resource: ['pedidoVenda'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Contato',
				name: 'contato',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Adicionar Contato',
				options: [
					{
						displayName: 'Dados do Contato',
						name: 'contatoData',
						values: [
							{
								displayName: 'ID do Contato',
								name: 'id',
								type: 'number',
								default: 0,
								description: 'ID do contato vinculado ao pedido',
							},
							{
								displayName: 'Nome',
								name: 'nome',
								type: 'string',
								default: '',
								description: 'Nome do contato',
							},
							{
								displayName: 'Tipo Pessoa',
								name: 'tipoPessoa',
								type: 'options',
								options: [
									{ name: 'Juridica', value: 'J' },
									{ name: 'Fisica', value: 'F' },
									{ name: 'Estrangeiro', value: 'E' },
								],
								default: 'F',
								description: 'Tipo de pessoa do contato',
							},
							{
								displayName: 'Numero Documento',
								name: 'numeroDocumento',
								type: 'string',
								default: '',
								description: 'CPF ou CNPJ do contato',
							},
						],
					},
				],
				description: 'Dados do contato vinculado ao pedido',
			},
			{
				displayName: 'Data',
				name: 'data',
				type: 'string',
				default: '',
				description: 'Data do pedido (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Prevista',
				name: 'dataPrevista',
				type: 'string',
				default: '',
				description: 'Data prevista de entrega (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Saida',
				name: 'dataSaida',
				type: 'string',
				default: '',
				description: 'Data de saida (AAAA-MM-DD HH:mm:ss)',
			},
			{
				displayName: 'Numero',
				name: 'numero',
				type: 'number',
				default: 0,
				description: 'Numero do pedido',
			},
			{
				displayName: 'Numero da Loja',
				name: 'numeroLoja',
				type: 'string',
				default: '',
				description: 'Numero do pedido na loja',
			},
			{
				displayName: 'ID Loja',
				name: 'loja',
				type: 'number',
				default: 0,
				description: 'ID da loja',
			},
			{
				displayName: 'ID Natureza da Operacao',
				name: 'naturezaOperacao',
				type: 'number',
				default: 0,
				description: 'ID da natureza da operacao',
			},
			{
				displayName: 'ID Vendedor',
				name: 'vendedor',
				type: 'number',
				default: 0,
				description: 'ID do vendedor',
			},
			{
				displayName: 'Observacoes',
				name: 'observacoes',
				type: 'string',
				default: '',
				description: 'Observacoes do pedido',
			},
			{
				displayName: 'Observacoes Internas',
				name: 'observacoesInternas',
				type: 'string',
				default: '',
				description: 'Observacoes internas do pedido',
			},
			{
				displayName: 'Desconto',
				name: 'desconto',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor do desconto',
			},
			{
				displayName: 'Outra Despesa',
				name: 'outrasDespesas',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor de outras despesas',
			},
			{
				displayName: 'Frete por Conta',
				name: 'fretePorConta',
				type: 'options',
				options: [
					{ name: 'Contratacao do Frete por conta do Remetente (CIF)', value: 0 },
					{ name: 'Contratacao do Frete por conta do Destinatario (FOB)', value: 1 },
					{ name: 'Contratacao do Frete por conta de Terceiros', value: 2 },
					{ name: 'Transporte Proprio por conta do Remetente', value: 3 },
					{ name: 'Transporte Proprio por conta do Destinatario', value: 4 },
					{ name: 'Sem Ocorrencia de Transporte', value: 9 },
				],
				default: 9,
				description: 'Modalidade de frete',
			},
			{
				displayName: 'Frete',
				name: 'frete',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor do frete',
			},
			{
				displayName: 'Itens',
				name: 'itens',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				default: {},
				placeholder: 'Adicionar Item',
				options: [
					{
						displayName: 'Item',
						name: 'itemData',
						values: [
							{
								displayName: 'ID do Produto',
								name: 'produto',
								type: 'number',
								default: 0,
								description: 'ID do produto',
							},
							{
								displayName: 'Descricao',
								name: 'descricao',
								type: 'string',
								default: '',
								description: 'Descricao do item',
							},
							{
								displayName: 'Quantidade',
								name: 'quantidade',
								type: 'number',
								typeOptions: { numberPrecision: 4 },
								default: 1,
								description: 'Quantidade do item',
							},
							{
								displayName: 'Valor Unitario',
								name: 'valor',
								type: 'number',
								typeOptions: { numberPrecision: 4 },
								default: 0,
								description: 'Valor unitario do item',
							},
							{
								displayName: 'Codigo',
								name: 'codigo',
								type: 'string',
								default: '',
								description: 'Codigo do produto/item',
							},
							{
								displayName: 'Unidade',
								name: 'unidade',
								type: 'string',
								default: 'UN',
								description: 'Unidade de medida do item',
							},
							{
								displayName: 'Desconto',
								name: 'desconto',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
								description: 'Valor de desconto do item',
							},
							{
								displayName: 'Aliquota IPI',
								name: 'aliquotaIPI',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
								description: 'Aliquota de IPI do item',
							},
						],
					},
				],
				description: 'Itens do pedido',
			},
			{
				displayName: 'Parcelas',
				name: 'parcelas',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				default: {},
				placeholder: 'Adicionar Parcela',
				options: [
					{
						displayName: 'Parcela',
						name: 'parcelaData',
						values: [
							{
								displayName: 'Data de Vencimento',
								name: 'dataVencimento',
								type: 'string',
								default: '',
								description: 'Data de vencimento da parcela (AAAA-MM-DD)',
							},
							{
								displayName: 'Valor',
								name: 'valor',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
								description: 'Valor da parcela',
							},
							{
								displayName: 'Observacoes',
								name: 'observacoes',
								type: 'string',
								default: '',
								description: 'Observacoes da parcela',
							},
							{
								displayName: 'ID Forma de Pagamento',
								name: 'formaPagamento',
								type: 'number',
								default: 0,
								description: 'ID da forma de pagamento',
							},
						],
					},
				],
				description: 'Parcelas do pedido',
			},
			{
				displayName: 'Transporte',
				name: 'transporte',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Adicionar Transporte',
				options: [
					{
						displayName: 'Dados do Transporte',
						name: 'transporteData',
						values: [
							{
								displayName: 'ID Contato Transportadora',
								name: 'contato',
								type: 'number',
								default: 0,
								description: 'ID do contato da transportadora',
							},
							{
								displayName: 'Frete por Conta',
								name: 'fretePorConta',
								type: 'options',
								options: [
									{ name: 'Remetente (CIF)', value: 0 },
									{ name: 'Destinatario (FOB)', value: 1 },
									{ name: 'Terceiros', value: 2 },
									{ name: 'Proprio Remetente', value: 3 },
									{ name: 'Proprio Destinatario', value: 4 },
									{ name: 'Sem transporte', value: 9 },
								],
								default: 9,
								description: 'Modalidade de frete',
							},
							{
								displayName: 'Frete',
								name: 'frete',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
								description: 'Valor do frete',
							},
							{
								displayName: 'Quantidade de Volumes',
								name: 'quantidadeVolumes',
								type: 'number',
								default: 0,
								description: 'Quantidade de volumes',
							},
							{
								displayName: 'Peso Bruto',
								name: 'pesoBruto',
								type: 'number',
								typeOptions: { numberPrecision: 3 },
								default: 0,
								description: 'Peso bruto total',
							},
							{
								displayName: 'Servico de Correios',
								name: 'servicoCorreios',
								type: 'string',
								default: '',
								description: 'Servico dos correios utilizado',
							},
						],
					},
				],
				description: 'Dados de transporte do pedido',
			},
		],
	},

	// ----------------------------------
	//         pedidoVenda: update - updateFields
	// ----------------------------------
	{
		displayName: 'Campos para Atualizar',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Adicionar Campo',
		default: {},
		displayOptions: {
			show: {
				resource: ['pedidoVenda'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Contato',
				name: 'contato',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Adicionar Contato',
				options: [
					{
						displayName: 'Dados do Contato',
						name: 'contatoData',
						values: [
							{
								displayName: 'ID do Contato',
								name: 'id',
								type: 'number',
								default: 0,
							},
							{
								displayName: 'Nome',
								name: 'nome',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Tipo Pessoa',
								name: 'tipoPessoa',
								type: 'options',
								options: [
									{ name: 'Juridica', value: 'J' },
									{ name: 'Fisica', value: 'F' },
									{ name: 'Estrangeiro', value: 'E' },
								],
								default: 'F',
							},
							{
								displayName: 'Numero Documento',
								name: 'numeroDocumento',
								type: 'string',
								default: '',
							},
						],
					},
				],
			},
			{
				displayName: 'Data',
				name: 'data',
				type: 'string',
				default: '',
				description: 'Data do pedido (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Prevista',
				name: 'dataPrevista',
				type: 'string',
				default: '',
				description: 'Data prevista de entrega (AAAA-MM-DD)',
			},
			{
				displayName: 'Numero',
				name: 'numero',
				type: 'number',
				default: 0,
				description: 'Numero do pedido',
			},
			{
				displayName: 'ID Loja',
				name: 'loja',
				type: 'number',
				default: 0,
				description: 'ID da loja',
			},
			{
				displayName: 'ID Vendedor',
				name: 'vendedor',
				type: 'number',
				default: 0,
				description: 'ID do vendedor',
			},
			{
				displayName: 'Observacoes',
				name: 'observacoes',
				type: 'string',
				default: '',
				description: 'Observacoes do pedido',
			},
			{
				displayName: 'Observacoes Internas',
				name: 'observacoesInternas',
				type: 'string',
				default: '',
				description: 'Observacoes internas do pedido',
			},
			{
				displayName: 'Desconto',
				name: 'desconto',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor do desconto',
			},
			{
				displayName: 'Frete',
				name: 'frete',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor do frete',
			},
			{
				displayName: 'Outra Despesa',
				name: 'outrasDespesas',
				type: 'number',
				typeOptions: { numberPrecision: 2 },
				default: 0,
				description: 'Valor de outras despesas',
			},
			{
				displayName: 'Itens',
				name: 'itens',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				default: {},
				placeholder: 'Adicionar Item',
				options: [
					{
						displayName: 'Item',
						name: 'itemData',
						values: [
							{
								displayName: 'Indice do Item',
								name: 'indice',
								type: 'number',
								default: 0,
								description: 'Indice (posicao) do item a ser atualizado (comeca em 0)',
							},
							{
								displayName: 'ID do Produto',
								name: 'produto',
								type: 'number',
								default: 0,
							},
							{
								displayName: 'Descricao',
								name: 'descricao',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Quantidade',
								name: 'quantidade',
								type: 'number',
								typeOptions: { numberPrecision: 4 },
								default: 1,
							},
							{
								displayName: 'Valor Unitario',
								name: 'valor',
								type: 'number',
								typeOptions: { numberPrecision: 4 },
								default: 0,
							},
							{
								displayName: 'Codigo',
								name: 'codigo',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Unidade',
								name: 'unidade',
								type: 'string',
								default: 'UN',
							},
							{
								displayName: 'Desconto',
								name: 'desconto',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
							},
						],
					},
				],
			},
			{
				displayName: 'Parcelas',
				name: 'parcelas',
				type: 'fixedCollection',
				typeOptions: { multipleValues: true },
				default: {},
				placeholder: 'Adicionar Parcela',
				options: [
					{
						displayName: 'Parcela',
						name: 'parcelaData',
						values: [
							{
								displayName: 'Indice da Parcela',
								name: 'indice',
								type: 'number',
								default: 0,
								description: 'Indice (posicao) da parcela a ser atualizada (comeca em 0)',
							},
							{
								displayName: 'Data de Vencimento',
								name: 'dataVencimento',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Valor',
								name: 'valor',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
							},
							{
								displayName: 'Observacoes',
								name: 'observacoes',
								type: 'string',
								default: '',
							},
							{
								displayName: 'ID Forma de Pagamento',
								name: 'formaPagamento',
								type: 'number',
								default: 0,
							},
						],
					},
				],
			},
			{
				displayName: 'Transporte',
				name: 'transporte',
				type: 'fixedCollection',
				default: {},
				placeholder: 'Adicionar Transporte',
				options: [
					{
						displayName: 'Dados do Transporte',
						name: 'transporteData',
						values: [
							{
								displayName: 'ID Contato Transportadora',
								name: 'contato',
								type: 'number',
								default: 0,
							},
							{
								displayName: 'Frete por Conta',
								name: 'fretePorConta',
								type: 'options',
								options: [
									{ name: 'Remetente (CIF)', value: 0 },
									{ name: 'Destinatario (FOB)', value: 1 },
									{ name: 'Terceiros', value: 2 },
									{ name: 'Proprio Remetente', value: 3 },
									{ name: 'Proprio Destinatario', value: 4 },
									{ name: 'Sem transporte', value: 9 },
								],
								default: 9,
							},
							{
								displayName: 'Frete',
								name: 'frete',
								type: 'number',
								typeOptions: { numberPrecision: 2 },
								default: 0,
							},
							{
								displayName: 'Quantidade de Volumes',
								name: 'quantidadeVolumes',
								type: 'number',
								default: 0,
							},
							{
								displayName: 'Peso Bruto',
								name: 'pesoBruto',
								type: 'number',
								typeOptions: { numberPrecision: 3 },
								default: 0,
							},
						],
					},
				],
			},
		],
	},

	// ----------------------------------
	//         pedidoVenda: getAll - returnAll
	// ----------------------------------
	{
		displayName: 'Retornar Todos',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: {
			show: {
				resource: ['pedidoVenda'],
				operation: ['getAll'],
			},
		},
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limite',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: {
			minValue: 1,
			maxValue: 100,
		},
		displayOptions: {
			show: {
				resource: ['pedidoVenda'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		description: 'Max number of results to return',
	},

	// ----------------------------------
	//         pedidoVenda: getAll - filters
	// ----------------------------------
	{
		displayName: 'Filtros',
		name: 'filters',
		type: 'collection',
		placeholder: 'Adicionar Campo',
		default: {},
		displayOptions: {
			show: {
				resource: ['pedidoVenda'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Data Inclusao Inicial',
				name: 'dataInclusaoInicial',
				type: 'string',
				default: '',
				description: 'Data de inclusao inicial (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Inclusao Final',
				name: 'dataInclusaoFinal',
				type: 'string',
				default: '',
				description: 'Data de inclusao final (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Alteracao Inicial',
				name: 'dataAlteracaoInicial',
				type: 'string',
				default: '',
				description: 'Data de alteracao inicial (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Alteracao Final',
				name: 'dataAlteracaoFinal',
				type: 'string',
				default: '',
				description: 'Data de alteracao final (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Prevista Inicial',
				name: 'dataPrevistaInicial',
				type: 'string',
				default: '',
				description: 'Data prevista inicial (AAAA-MM-DD)',
			},
			{
				displayName: 'Data Prevista Final',
				name: 'dataPrevistaFinal',
				type: 'string',
				default: '',
				description: 'Data prevista final (AAAA-MM-DD)',
			},
			{
				displayName: 'ID Situacao',
				name: 'idSituacao',
				type: 'number',
				default: 0,
				description: 'ID da situacao do pedido',
			},
			{
				displayName: 'ID Contato',
				name: 'idContato',
				type: 'number',
				default: 0,
				description: 'ID do contato vinculado',
			},
			{
				displayName: 'ID Loja',
				name: 'idLoja',
				type: 'number',
				default: 0,
				description: 'ID da loja',
			},
			{
				displayName: 'Numero',
				name: 'numero',
				type: 'number',
				default: 0,
				description: 'Numero do pedido',
			},
			{
				displayName: 'ID Vendedor',
				name: 'idVendedor',
				type: 'number',
				default: 0,
				description: 'ID do vendedor',
			},
			{
				displayName: 'Numero da Loja',
				name: 'numeroLoja',
				type: 'string',
				default: '',
				description: 'Numero do pedido na loja',
			},
		],
	},
];
